# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 09:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CertInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=20)),
                ('organization', models.CharField(max_length=20)),
                ('addr', models.CharField(max_length=30)),
                ('system_name', models.CharField(max_length=20)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('isCompatible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MonitorInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_date', models.DateTimeField()),
                ('freq', models.IntegerField(default=5)),
                ('state', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=12)),
                ('cert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.CertInfo')),
            ],
        ),
    ]
