# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 03:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certinfo',
            name='end_date',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='certinfo',
            name='start_date',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='monitorinfo',
            name='current_date',
            field=models.CharField(max_length=20),
        ),
    ]
