# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 01:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_auto_20171116_1020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitorinfo',
            name='current_date',
        ),
        migrations.RemoveField(
            model_name='monitorinfo',
            name='freq',
        ),
        migrations.RemoveField(
            model_name='monitorinfo',
            name='state',
        ),
    ]
